apiVersion: webapp.alainrk.com/v1
kind: AppService
metadata:
  labels:
    app.kubernetes.io/name: appservice
    app.kubernetes.io/instance: appservice-sample
    app.kubernetes.io/part-of: kop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kop
  name: appservice-sample
spec:
  # TODO(user): Add fields here
